name: 'Get current package version'
description: 'Get the current version of the npm package'
branding:
  color: 'gray-dark'
  icon: 'align-center'
inputs:
  path:
    required: false
    default: '.'
    description: 'Path to package.json file (directories only), e.g. packages/mypackage/'
outputs:
  fullVersion:
    description: 'Full version defined in the package.json file'
  fullRuntime:
    description: 'Full runtime defined in the package.json file'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.path }}
